Control del resultado del sonarqube

diff --git a/.github/workflows/workflowDevSecOps.yml b/.github/workflows/workflowDevSecOps.yml
--- a/.github/workflows/workflowDevSecOps.yml
+++ b/.github/workflows/workflowDevSecOps.yml
@@ -33,3 +33,9 @@ jobs:
             -Dsonar.organization=devsecops-usach
             -Dsonar.projectKey=devsecops-usach_laboratorio-final
             -Dsonar.branch.name=revisiones
+
+     - name: Revision de resultado de SonarQube
+        if: steps.sonarqube-quality-gate-check.outputs.quality-gate-status != 'OK'
+        run: |
+          echo "Quality Gate failed!"
+          exit 1
